version: '2'
services:
  eureka-server:
    image: estimator-app/eureka-server:1
    ports:
    - 8761:8761
  configuration-server:
    image: estimator-app/configuration-server:1
    ports:
    - 8888:8888
    environment:
      EUREKASERVER_URI: http://eureka-server:8761/eureka/
      EUREKASERVER_PORT: '8761'
      ENCRYPT_KEY: ${ENCRYPT_KEY}
  database:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      POSTGRES_DB: estimator_local
  project-service:
    image: estimator-app/project-service:1
    ports:
    - 8080:8080
    environment:
      PROFILE: default
      SERVER_PORT: '8080'
      CONFIGSERVER_URI: http://configuration-server:8888
      CONFIGSERVER_PORT: '8888'
      EUREKASERVER_URI: http://eureka-server:8761/eureka/
      EUREKASERVER_PORT: '8761'
      DATABASESERVER_PORT: '5432'
      ENCRYPT_KEY: ${ENCRYPT_KEY}
  organization-service:
    image: estimator-app/organization-service:1
    ports:
    - 8085:8085
    environment:
      PROFILE: default
      SERVER_PORT: '8085'
      CONFIGSERVER_URI: http://configuration-server:8888
      EUREKASERVER_URI: http://eureka-server:8761/eureka/
      EUREKASERVER_PORT: '8761'
      CONFIGSERVER_PORT: '8888'
      DATABASESERVER_PORT: '5432'
      ENCRYPT_KEY: ${ENCRYPT_KEY}