server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/vdharna/estimator-app
          searchPaths: config-repo/organization-service, config-repo/project-service
          username: vdharna
          password: G0$harks
