spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/estimator_local"
    username: postgres
    password: "{cipher}5db65212ef51d3dec0ec5e108cf6a6b7a5517fdab8b9fd6087759da5a3f92b97"

example:
  property: "Hello"
